meta_product_name: "Awe Inspiring Consulting"
meta_title: "Awe Inspiring Consulting - Workplace Wellness - Corporate Health - Professional Lifestyle Awareness"
meta_description: "Clients and professionals choose awe Inspiring Consulting because of our people. We have specific expertise and experience in performance management."
meta_image: "bluestairs.jpg" # should exist in `app/assets/images/`
